* 现在信息结构存在问题
** 数据分散
*** 小的层面
从初高中开始就很抗拒做笔记，因为做过之后我基本不会看第二遍。
以数学笔记为例，我有一个课堂笔记，也有一个错题本，它们可能都属于同一个知识点，但是它们同时又分别属于笔记和错题，在纸质笔记本中是物理隔离的。
** 树状结构的缺陷
*** 首先是僵化的前提假设
比如杜威十字编码，一开始就假设了固定的结构，并且禁止拓展
*** 分支天然就会重叠，于是导致二义性
比如js和cpp都有作用域原理，也有基础数据结构。在学习作用域的时候也会包含js和cpp的作用域介绍。
如果重叠的多了，那就可能存在多分拷贝。
** 双向链接的缺陷
*** 基于链接，而链接则隐藏了具体的细节
*** 在展示图的时候，产生关联的原因是被忽略的
** 无法自动聚合
*** 这是很重要的问题，根源是信息本质上是互相孤立的，所以需要主动通过链接关联
* 解决方案
** 将信息当作集合，实现树状结构
用通过集合的重叠来实现经典的树状结构
比如如果存在3个基础集合 A，B，C，如果存在以 (A,B) 表示 A和B的交集，也存在 （A,B,C) 交集，这些交集也是这几个集合的重叠部分。因为一个集合和其他集合的交集是自己的真子集的特性，这样我们就有了 A 集合中包含 (A,B)，后者又包含了 (A,B,C)。
如果忽略真子集中和父级重复的部分，就会得到 A 的信息的结构：
 A
 ｜- B
     | - C
** 因为交集信息自动聚合
如上所述，当 存在了 (A,B) 这个交集的同时，B的结构也会包含 A：
 B
 | - A
     | - C
所以信息会自动聚合，也无需链接，更无需双向链接了
** 使用 list 表示交集，并借鉴 lisp 实现对 list 的操作以及对操作的操作
** 描述一切信息
比如聊天、博客、论坛，全都可以视作一些集合，然后用 lisp 操作来快速编辑这些集合。
比如：
使用表达式 (.chat @alice @bob) 创建 一个包含这两个用户的聊天集合。
当然也可以实现notion那样的数据库管理
* 蕴含思想
** 道
大道至简，但又衍生万物
** lisp
无限扩展，自扩展
** 全息学
物理学有一种假设是黑洞的所有信息都蕴含在其表面上
** 虫洞
如果集合就是宇宙，拿每一个交集都相当于一个虫洞
** 宇宙一体观
中国易学的基础就是认为世界是一团气，所有事物都互相关联并且会互相影响
** 佛教观念
一花一世界
* 要求
** 批判性思考此课题、本文提出的解决方案的价值与意义
不要美化或者附和。
** 和我一起深入描述问题、完善方案
** 在理解项目本质的基础后，先帮我思考一个好的项目名
曾用名：lisct （list + intersection, 再考虑到 lisct 是匈牙利语中的“列表”）
想要的意向：重叠、桥、虫洞、层、列表
